//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Compteur
{
    private double vitesse;

    public double Vitesse
    {
        get { return vitesse; }
        set { vitesse = value; }
    }

    private double km;

    public double Km
    {
        get { return km; }
        set { km = value; }
    }

    private static double vitesseMax = 130;

	public Compteur()
	{
        vitesse = 0;
        km = 0;
	}

}

