//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Reservoir
{
    private int capacite;

    public int Capacite
    {
        get { return capacite; }
        set { capacite = value; }
    }

    private int contenu;

    public int Contenu
    {
        get { return contenu; }
        set { contenu = value; }
    }

	public Reservoir(int puissance)
	{
        if (puissance > 6)
            capacite = 60;
        else
            capacite = 40;
        contenu = capacite;
	}

	public void diminuer(double conso, double km)
	{
		contenu -= (int)((conso*km)/100);
	}

    public void diminuer()
    {
        contenu = 0;
    }

	public double distanceMaxi(double conso)
	{
		return (contenu / (conso/100));
	}

	public void remplir()
	{
		contenu = capacite;
	}

}

