//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Simulateur
{

	public Simulateur(int puissance, string nimat, int km, double vitesse)
	{
		Voiture voiture = new Voiture (puissance, nimat);
        voiture.rouler(km, vitesse);
	}

}

