//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Voiture
{
	private string nimat
	{
		get;
		set;
	}

	private int puissance
	{
		get;
		set;
	}

	public Reservoir reservoir
	{
		get;
		set;
	}

	public Compteur compteur
	{
		get;
		set;
	}

    private static int prixEssence = 1;

    private static int prixDepan = 100;

	public Voiture(int puissance, string nimat)
	{
        this.nimat = nimat;
        this.puissance = puissance;
        reservoir = new Reservoir(puissance);
        compteur = new Compteur();
	}

	public void stopper()
	{
	}

	public void rouler(int km, double vitesse)
	{
        double kmRestant = km;
		compteur.Vitesse = vitesse;
        double prix = 0;
        double distanceMaxi = reservoir.distanceMaxi(conso());
        int i = 0;
        Console.WriteLine(conso());
        Console.WriteLine();
        while(kmRestant > distanceMaxi)
        {
            compteur.Km += distanceMaxi;
            reservoir.diminuer();
            prix += (tomberEnPanne());
            kmRestant -= distanceMaxi;
            i++;
            Console.WriteLine("Panne n°" + i);
            Console.WriteLine("Il reste " + Math.Round(kmRestant,2) + "km à parcourir.");
            Console.WriteLine("Le prix est de " + Math.Round(prix,2) + " euros.");
            Console.WriteLine("========================================================");
        }
        compteur.Km += kmRestant;
        reservoir.diminuer(conso(),kmRestant);
        Console.WriteLine(reservoir.Capacite);
        Console.WriteLine(reservoir.Contenu);
        prix += (reservoir.Contenu - reservoir.Capacite) * prixEssence;
        prix = Math.Round(prix, 2);
        Console.WriteLine("Le prix final est de " + prix + " euros.");
        Console.ReadLine();
	}

	public double tomberEnPanne()
	{
        return (prixDepan + fairePlein()) ;
	}

	public double fairePlein()
	{
        reservoir.remplir();
        return (prixEssence * reservoir.Capacite);
	}

	public double conso()
	{
        int p = puissance;
        double vitesse = compteur.Vitesse;
        double conso = 0;
        if (vitesse < 80)
        {
            conso = 6;
        }
        else if (vitesse < 100)
        {
            conso = 7;
        }
        else if (vitesse < 120)
        {
            conso = 8;
        }
        else if (vitesse <= 130)
        {
            conso = 9;
        }
        while (p - 4 > 0)
            {
                conso *= 1.0015;
                p--;
            }
        return conso;
	}

}

