//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Dessin
{
    private Rectangle[] lesRectangles;
    int nb = 0;

	public Dessin(int nbMax)
	{
        lesRectangles = new Rectangle[nbMax];
	}

	public void AjoutRectangle(Rectangle r)
	{
        if (nb < lesRectangles.Length)
        {
            lesRectangles[nb] = r;
            nb++;
        }
	}

	public virtual double CalculeSurface()
	{
        double s = 0;
        for (int i = 0; i<=nb; i++)
        {
            s += lesRectangles[i].CalculeSurface();
        }
        return (s);
	}

	public void SetPosition(Point pt1)
	{
        for (int i = 0; i <= nb; i++)
        {
            lesRectangles[i].SetPosition(pt1);
        }
	}

}

