//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Point
{
    private double y;

    public double Y
    {
        get { return y; }
        set { y = value; }
    }

    private double x;

    public double X
    {
        get { return x; }
        set { x = value; }
    }

	public Point(double x, double y)
	{
        this.x = x;
        this.y = y;
	}

	public bool EstEgal(Point pt)
	{
        return ((this.x == pt.x) && (this.y == pt.y));
	}

}

