//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class TestZoomable
{
	public List<IZoomable> lesIZoomables
	{
		get;
		set;
	}

	public TestZoomable(List<IZoomable> lesIZoomables, double z)
	{
        this.lesIZoomables = lesIZoomables;
        TestAire();
        TestVolume();
        TestZoom(z);
        TestAire();
        TestVolume();
	}

    public void TestZoom(double z)
    {
        foreach (IZoomable zoomable in lesIZoomables)
        {
            zoomable.zoom(z);
        }
    }

    public void TestVolume()
    {
        foreach (IZoomable zoomable in lesIZoomables)
        {
            Console.WriteLine(zoomable.volume());
        }
    }

    public void TestAire()
    {
        foreach (IZoomable zoomable in lesIZoomables)
        {
            Console.WriteLine(zoomable.aire());
        }
    }
}

