//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Dessin
{
	private IEnumerable<Rectangle> lesRectangles
	{
		get;
		set;
	}

	public Dessin(int nb)
	{
	}

	public void AjoutRectangle(Rectangle r)
	{
		throw new System.NotImplementedException();
	}

	public virtual double CalculeSurface()
	{
		throw new System.NotImplementedException();
	}

	public void SetPosition()
	{
		throw new System.NotImplementedException();
	}

}

