//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Point
{
	private double y
	{
		get;
		set;
	}

	private double x
	{
		get;
		set;
	}

	public Point(double x, double y)
	{
	}

	public bool EstEgal(Point pt1, Point pt2)
	{
		throw new System.NotImplementedException();
	}

}

