//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Rectangle
{
	private Point pt2
	{
		get;
		set;
	}

	private Point pt1
	{
		get;
		set;
	}

	public Rectangle(Point pt1, Point pt2)
	{
	}

	public Rectangle(Point pt1, double l1, double l2)
	{
	}

	public Rectangle(double l1, double l2, double l3, double l4)
	{
	}

	public double CalculeSurface()
	{
		throw new System.NotImplementedException();
	}

	public void SetPosition(Point pt1)
	{
		throw new System.NotImplementedException();
	}

	public bool EstEgal(Rectangle r)
	{
		throw new System.NotImplementedException();
	}

}

